"""initial_sor_schema

Revision ID: bda52b107059
Revises:
Create Date: 2026-07-17 23:20:35.812643

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bda52b107059"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_catalog",
        sa.Column("drive_file_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("folder_path", sa.Text(), nullable=True),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("md5_checksum", sa.String(length=64), nullable=True),
        sa.Column("doc_category", sa.String(length=64), nullable=True),
        sa.Column("doc_subtype", sa.String(length=64), nullable=True),
        sa.Column("drawing_number", sa.String(length=128), nullable=True),
        sa.Column("motor_type_code", sa.String(length=128), nullable=True),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_catalog_doc_category"),
        "document_catalog",
        ["doc_category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_catalog_drawing_number"),
        "document_catalog",
        ["drawing_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_catalog_drive_file_id"),
        "document_catalog",
        ["drive_file_id"],
        unique=True,
    )
    op.create_table(
        "drawing_numbers",
        sa.Column("drawing_number", sa.String(length=128), nullable=False),
        sa.Column("normalized", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_drawing_numbers_drawing_number"),
        "drawing_numbers",
        ["drawing_number"],
        unique=True,
    )
    op.create_index(
        op.f("ix_drawing_numbers_normalized"),
        "drawing_numbers",
        ["normalized"],
        unique=False,
    )
    op.create_table(
        "gdrive_sync_state",
        sa.Column("folder_id", sa.String(length=128), nullable=False),
        sa.Column("page_token", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("files_discovered", sa.Integer(), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gdrive_sync_state_folder_id"),
        "gdrive_sync_state",
        ["folder_id"],
        unique=True,
    )
    op.create_table(
        "plants",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plants_code"), "plants", ["code"], unique=True)
    op.create_table(
        "product_lines",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("oem", sa.String(length=128), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_lines_code"), "product_lines", ["code"], unique=True
    )
    op.create_table(
        "roles",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_code"), "roles", ["code"], unique=True)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "assets",
        sa.Column("asset_type", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("asset_tag", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("plant_id", sa.String(length=36), nullable=True),
        sa.Column("product_line_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_line_id"],
            ["product_lines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assets_asset_tag"), "assets", ["asset_tag"], unique=False)
    op.create_index(
        op.f("ix_assets_asset_type"), "assets", ["asset_type"], unique=False
    )
    op.create_index(op.f("ix_assets_plant_id"), "assets", ["plant_id"], unique=False)
    op.create_index(
        op.f("ix_assets_product_line_id"), "assets", ["product_line_id"], unique=False
    )
    op.create_table(
        "audit_events",
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=True),
        sa.Column("resource_id", sa.String(length=36), nullable=True),
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_actor_user_id"),
        "audit_events",
        ["actor_user_id"],
        unique=False,
    )
    op.create_table(
        "documents",
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("doc_type", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("storage_uri", sa.String(length=1024), nullable=True),
        sa.Column("catalog_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["catalog_id"],
            ["document_catalog.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_documents_catalog_id"), "documents", ["catalog_id"], unique=False
    )
    op.create_index(
        op.f("ix_documents_doc_type"), "documents", ["doc_type"], unique=False
    )
    op.create_index(op.f("ix_documents_status"), "documents", ["status"], unique=False)
    op.create_table(
        "motor_families",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("product_line_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_line_id"],
            ["product_lines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "product_line_id", "code", name="uq_motor_family_line_code"
        ),
    )
    op.create_index(
        op.f("ix_motor_families_code"), "motor_families", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_motor_families_product_line_id"),
        "motor_families",
        ["product_line_id"],
        unique=False,
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_id", name="uq_user_role"),
    )
    op.create_index(
        op.f("ix_user_roles_role_id"), "user_roles", ["role_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_roles_user_id"), "user_roles", ["user_id"], unique=False
    )
    op.create_table(
        "document_asset_links",
        sa.Column("link_type", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_id", "asset_id", "link_type", name="uq_document_asset_link"
        ),
    )
    op.create_index(
        op.f("ix_document_asset_links_asset_id"),
        "document_asset_links",
        ["asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_asset_links_document_id"),
        "document_asset_links",
        ["document_id"],
        unique=False,
    )
    op.create_table(
        "document_drawing_links",
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("drawing_number_id", sa.String(length=36), nullable=False),
        sa.Column("sheet_id", sa.String(length=32), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["drawing_number_id"],
            ["drawing_numbers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_id", "drawing_number_id", name="uq_document_drawing_link"
        ),
    )
    op.create_index(
        op.f("ix_document_drawing_links_document_id"),
        "document_drawing_links",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_drawing_links_drawing_number_id"),
        "document_drawing_links",
        ["drawing_number_id"],
        unique=False,
    )
    op.create_table(
        "document_versions",
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("storage_uri", sa.String(length=1024), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "version", name="uq_document_version"),
    )
    op.create_index(
        op.f("ix_document_versions_document_id"),
        "document_versions",
        ["document_id"],
        unique=False,
    )
    op.create_table(
        "indexing_jobs",
        sa.Column("job_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("document_id", sa.String(length=36), nullable=True),
        sa.Column("catalog_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["catalog_id"],
            ["document_catalog.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_indexing_jobs_catalog_id"),
        "indexing_jobs",
        ["catalog_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_indexing_jobs_document_id"),
        "indexing_jobs",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_indexing_jobs_job_type"), "indexing_jobs", ["job_type"], unique=False
    )
    op.create_index(
        op.f("ix_indexing_jobs_status"), "indexing_jobs", ["status"], unique=False
    )
    op.create_table(
        "motor_models",
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("frame_size", sa.String(length=64), nullable=True),
        sa.Column("power_kw", sa.Float(), nullable=True),
        sa.Column("voltage", sa.String(length=64), nullable=True),
        sa.Column("ie_class", sa.String(length=32), nullable=True),
        sa.Column("poles", sa.Integer(), nullable=True),
        sa.Column("mounting", sa.String(length=64), nullable=True),
        sa.Column("cooling", sa.String(length=64), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("family_id", sa.String(length=36), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["motor_families.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id"),
        sa.UniqueConstraint("family_id", "code", name="uq_motor_model_family_code"),
    )
    op.create_index(
        op.f("ix_motor_models_code"), "motor_models", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_motor_models_family_id"), "motor_models", ["family_id"], unique=False
    )
    op.create_table(
        "motor_ai_summaries",
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("source_doc_ids", sa.JSON(), nullable=True),
        sa.Column("model_version", sa.String(length=64), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["motor_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_motor_ai_summaries_model_id"),
        "motor_ai_summaries",
        ["model_id"],
        unique=False,
    )
    op.create_table(
        "motor_aliases",
        sa.Column("alias", sa.String(length=255), nullable=False),
        sa.Column("alias_type", sa.String(length=64), nullable=False),
        sa.Column("model_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["motor_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_id", "alias", name="uq_motor_alias_model_alias"),
    )
    op.create_index(
        op.f("ix_motor_aliases_alias"), "motor_aliases", ["alias"], unique=False
    )
    op.create_index(
        op.f("ix_motor_aliases_model_id"), "motor_aliases", ["model_id"], unique=False
    )
    op.create_table(
        "motor_health_scores",
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("risk_level", sa.String(length=32), nullable=False),
        sa.Column("reasoning", sa.JSON(), nullable=True),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["motor_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_motor_health_scores_model_id"),
        "motor_health_scores",
        ["model_id"],
        unique=False,
    )
    op.create_table(
        "motor_recommendations",
        sa.Column("recommendations", sa.JSON(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=True),
        sa.Column("model_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["motor_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_motor_recommendations_model_id"),
        "motor_recommendations",
        ["model_id"],
        unique=False,
    )
    op.create_table(
        "motor_timeline_events",
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("event_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_estimated", sa.Boolean(), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=True),
        sa.Column("model_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["motor_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_motor_timeline_events_event_at"),
        "motor_timeline_events",
        ["event_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_motor_timeline_events_event_type"),
        "motor_timeline_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_motor_timeline_events_model_id"),
        "motor_timeline_events",
        ["model_id"],
        unique=False,
    )
    op.create_table(
        "motor_units",
        sa.Column("serial_number", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("commissioned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("model_id", sa.String(length=36), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["motor_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id"),
    )
    op.create_index(
        op.f("ix_motor_units_model_id"), "motor_units", ["model_id"], unique=False
    )
    op.create_index(
        op.f("ix_motor_units_serial_number"),
        "motor_units",
        ["serial_number"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_motor_units_serial_number"), table_name="motor_units")
    op.drop_index(op.f("ix_motor_units_model_id"), table_name="motor_units")
    op.drop_table("motor_units")
    op.drop_index(
        op.f("ix_motor_timeline_events_model_id"), table_name="motor_timeline_events"
    )
    op.drop_index(
        op.f("ix_motor_timeline_events_event_type"), table_name="motor_timeline_events"
    )
    op.drop_index(
        op.f("ix_motor_timeline_events_event_at"), table_name="motor_timeline_events"
    )
    op.drop_table("motor_timeline_events")
    op.drop_index(
        op.f("ix_motor_recommendations_model_id"), table_name="motor_recommendations"
    )
    op.drop_table("motor_recommendations")
    op.drop_index(
        op.f("ix_motor_health_scores_model_id"), table_name="motor_health_scores"
    )
    op.drop_table("motor_health_scores")
    op.drop_index(op.f("ix_motor_aliases_model_id"), table_name="motor_aliases")
    op.drop_index(op.f("ix_motor_aliases_alias"), table_name="motor_aliases")
    op.drop_table("motor_aliases")
    op.drop_index(
        op.f("ix_motor_ai_summaries_model_id"), table_name="motor_ai_summaries"
    )
    op.drop_table("motor_ai_summaries")
    op.drop_index(op.f("ix_motor_models_family_id"), table_name="motor_models")
    op.drop_index(op.f("ix_motor_models_code"), table_name="motor_models")
    op.drop_table("motor_models")
    op.drop_index(op.f("ix_indexing_jobs_status"), table_name="indexing_jobs")
    op.drop_index(op.f("ix_indexing_jobs_job_type"), table_name="indexing_jobs")
    op.drop_index(op.f("ix_indexing_jobs_document_id"), table_name="indexing_jobs")
    op.drop_index(op.f("ix_indexing_jobs_catalog_id"), table_name="indexing_jobs")
    op.drop_table("indexing_jobs")
    op.drop_index(
        op.f("ix_document_versions_document_id"), table_name="document_versions"
    )
    op.drop_table("document_versions")
    op.drop_index(
        op.f("ix_document_drawing_links_drawing_number_id"),
        table_name="document_drawing_links",
    )
    op.drop_index(
        op.f("ix_document_drawing_links_document_id"),
        table_name="document_drawing_links",
    )
    op.drop_table("document_drawing_links")
    op.drop_index(
        op.f("ix_document_asset_links_document_id"), table_name="document_asset_links"
    )
    op.drop_index(
        op.f("ix_document_asset_links_asset_id"), table_name="document_asset_links"
    )
    op.drop_table("document_asset_links")
    op.drop_index(op.f("ix_user_roles_user_id"), table_name="user_roles")
    op.drop_index(op.f("ix_user_roles_role_id"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(
        op.f("ix_motor_families_product_line_id"), table_name="motor_families"
    )
    op.drop_index(op.f("ix_motor_families_code"), table_name="motor_families")
    op.drop_table("motor_families")
    op.drop_index(op.f("ix_documents_status"), table_name="documents")
    op.drop_index(op.f("ix_documents_doc_type"), table_name="documents")
    op.drop_index(op.f("ix_documents_catalog_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_audit_events_actor_user_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_assets_product_line_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_plant_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_asset_type"), table_name="assets")
    op.drop_index(op.f("ix_assets_asset_tag"), table_name="assets")
    op.drop_table("assets")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_roles_code"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_product_lines_code"), table_name="product_lines")
    op.drop_table("product_lines")
    op.drop_index(op.f("ix_plants_code"), table_name="plants")
    op.drop_table("plants")
    op.drop_index(
        op.f("ix_gdrive_sync_state_folder_id"), table_name="gdrive_sync_state"
    )
    op.drop_table("gdrive_sync_state")
    op.drop_index(op.f("ix_drawing_numbers_normalized"), table_name="drawing_numbers")
    op.drop_index(
        op.f("ix_drawing_numbers_drawing_number"), table_name="drawing_numbers"
    )
    op.drop_table("drawing_numbers")
    op.drop_index(
        op.f("ix_document_catalog_drive_file_id"), table_name="document_catalog"
    )
    op.drop_index(
        op.f("ix_document_catalog_drawing_number"), table_name="document_catalog"
    )
    op.drop_index(
        op.f("ix_document_catalog_doc_category"), table_name="document_catalog"
    )
    op.drop_table("document_catalog")
    # ### end Alembic commands ###
